from flask import Flask, render_template, request

app = Flask(__name__)



colleges = {
    "iit bombay": {
        "Full Name": "Indian Institute of Technology Bombay",
        "Short Name": "IITB",
        "Location": "Powai, Mumbai, Maharashtra",
        "Established": "1958",
        "Type": "Government",
        "Courses Offered": "B.Tech, Dual Degree, M.Tech, MSc, MBA, PhD",
        "Admission": "JEE Advanced, GATE, JAM, CAT",
        "Fees": "Approx. ₹2.3 Lakh per year",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹36 LPA",
        "Highest Package": "₹2+ Crore (varies every year)",
        "Top Recruiters": "Google, Microsoft, Amazon, Apple, Qualcomm, Tata",
        "Hostel": "Available",
        "Library": "Central Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi, Labs, Medical Centre, Gym",
        "Official Website": "https://www.iitb.ac.in",
        "Review": "One of India's best engineering institutes.",
        "image": "iit_bombay.jpg"
    },
    "iit delhi": {
        "Full Name": "Indian Institute of Technology Delhi",
        "Short Name": "IITD",
        "Location": "New Delhi",
        "Established": "1961",
        "Type": "Government",
        "Courses Offered": "B.Tech, M.Tech, MSc, MBA, PhD",
        "Admission": "JEE Advanced, GATE, JAM, CAT",
        "Fees": "Approx. ₹2.4 Lakh per year",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹25 LPA",
        "Highest Package": "₹2+ Crore (varies every year)",
        "Top Recruiters": "Google, Microsoft, Amazon, Adobe, Goldman Sachs",
        "Hostel": "Available",
        "Library": "Central Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi, Labs, Medical Centre, Gym",
        "Official Website": "https://home.iitd.ac.in",
        "Review": "One of India's top engineering institutes.",
        "image": "iit_delhi.jpg"
    },
    "iit madras": {
        "Full Name": "Indian Institute of Technology Madras",
        "Short Name": "IITM",
        "Location": "Chennai, Tamil Nadu",
        "Established": "1959",
        "Type": "Government",
        "Courses Offered": "B.Tech, M.Tech, MSc, MBA, MA, PhD",
        "Admission": "JEE Advanced, GATE, JAM, CAT",
        "Fees": "Approx. ₹2.3 Lakh per year",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹22 LPA",
        "Highest Package": "₹1.5+ Crore (varies every year)",
        "Top Recruiters": "Google, Microsoft, Amazon, Qualcomm, Deloitte",
        "Hostel": "Available",
        "Library": "Central Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi, Labs, Medical Centre, Gym",
        "Official Website": "https://www.iitm.ac.in",
        "Review": "India's top-ranked engineering institute with excellent academics and research.",
        "image": "iit_madras.jpg"
    },
    "iit kanpur": {
        "Full Name": "Indian Institute of Technology Kanpur",
        "Short Name": "IITK",
        "Location": "Kanpur, Uttar Pradesh",
        "Established": "1959",
        "Type": "Government",
        "Courses Offered": "B.Tech, BS, M.Tech, MBA, MSc, PhD",
        "Admission": "JEE Advanced, GATE, JAM, CAT",
        "Fees": "Approx. ₹2.3 Lakh per year",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹26 LPA",
        "Highest Package": "₹2+ Crore (varies every year)",
        "Top Recruiters": "Google, Microsoft, Intel, Samsung, Oracle, Adobe",
        "Hostel": "Available",
        "Library": "Central Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi, Labs, Medical Centre, Gym, Auditorium",
        "Official Website": "https://www.iitk.ac.in",
        "Review": "Known for world-class research, innovation and excellent placements",
        "image": "iit_kanpur.jpg"
        
    },
    "iit kharagpur": {
        "Full Name": "Indian Institute of Technology Kharagpur",
        "Short Name": "IITKGP",
        "Location": "Kharagpur, West Bengal",
        "Established": "1951",
        "Type": "Government",
        "Courses Offered": "B.Tech, B.Arch, LLB, M.Tech, MBA, MSc, PhD",
        "Admission": "JEE Advanced, GATE, JAM, CAT",
        "Fees": "Approx. ₹2.3 Lakh per year",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹24 LPA",
        "Highest Package": "₹2+ Crore (varies every year)",
        "Top Recruiters": "Google, Microsoft, Amazon, Tata Steel, ISRO, Qualcomm",
        "Hostel": "Available",
        "Library": "Central Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi, Labs, Medical Centre, Gym, Stadium",
        "Official Website": "https://www.iitkgp.ac.in",
        "Review": "India's first IIT with a large campus, excellent academics and placements.",
        "image": "iit_kharagpur.jpg"
    },
    "iim ahmedabad": {
        "Full Name": "Indian Institute of Management Ahmedabad",
        "Short Name": "IIMA",
        "Location": "Ahmedabad, Gujarat",
        "Established": "1961",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), MBA-FABM, Executive MBA (PGPX), PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹26 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹35 LPA",
        "Highest Package": "Varies every year",
        "Top Recruiters": "McKinsey, BCG, Bain, Amazon, Google, Microsoft",
        "Hostel": "Available",
        "Library": "Vikram Sarabhai Library",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iima.ac.in",
        "Review": "India's top management institute with world-class faculty and placements.",
        "Why Choose": "Excellent academics, global reputation and outstanding placement opportunities.",
        "image": "iim_ahmedabad.jpg"
    },
    "iim bangalore": {
        "Full Name": "Indian Institute of Management Bangalore",
        "Short Name": "IIMB",
        "Location": "Bengaluru, Karnataka",
        "Established": "1973",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), Executive MBA, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹26 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹35 LPA",
        "Highest Package": "Varies every year",
        "Top Recruiters": "Amazon, Microsoft, BCG, Accenture, Goldman Sachs",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iimb.ac.in",
        "Review": "One of India's premier management institutes with excellent placements.",
        "Why Choose": "Strong industry connections, global recognition and outstanding faculty.",
        "image": "iim_bangalore.jpg"
    },
    "iim calcutta": {
        "Full Name": "Indian Institute of Management Calcutta",
        "Short Name": "IIMC",
        "Location": "Kolkata, West Bengal",
        "Established": "1961",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), Executive MBA, MBAEx, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹27 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹35 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "BCG, Bain, McKinsey, Amazon, Microsoft, Deloitte",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iimcal.ac.in",
        "Review": "One of India's oldest and most prestigious IIMs with excellent placements.",
        "Why Choose": "Outstanding faculty, strong alumni network and global corporate reputation.",
        "image": "iim_calcutta.jpg"
    },
    "iim lucknow": {
        "Full Name": "Indian Institute of Management Lucknow",
        "Short Name": "IIML",
        "Location": "Lucknow, Uttar Pradesh",
        "Established": "1984",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), Executive MBA, IPMX, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹21 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹32 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "BCG, Deloitte, EY, Amazon, Accenture, Infosys",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iiml.ac.in",
        "Review": "One of India's leading management institutes with excellent academics and placements.",
        "Why Choose": "Strong alumni network, excellent faculty and high placement records.",
        "image": "iim_lucknow.jpg"
    },
    "iim mumbai": {
        "Full Name": "Indian Institute of Management Mumbai",
        "Short Name": "IIMM",
        "Location": "Mumbai, Maharashtra",
        "Established": "1963 (as NITIE), IIM Status: 2023",
        "Type": "Government",
        "Courses Offered": "MBA, MBA (Operations & Supply Chain), Executive MBA, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹21 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹31 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "Amazon, Deloitte, PwC, Accenture, Tata, Reliance",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://iimmumbai.ac.in",
        "Review": "One of India's leading management institutes, especially in operations and supply chain management.",
        "Why Choose": "Excellent placements, industry-focused curriculum, and strong corporate connections.",
        "image": "iim_mumbai.jpg"
    },
    "iim kozhikode": {
        "Full Name": "Indian Institute of Management Kozhikode",
        "Short Name": "IIMK",
        "Location": "Kozhikode, Kerala",
        "Established": "1996",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), Executive MBA, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹22 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹28 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "Amazon, Deloitte, EY, Accenture, Infosys",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iimk.ac.in",
        "Review": "One of India's fastest growing IIMs with excellent academics and placements.",
        "Why Choose": "Beautiful campus, strong academics, international exposure and excellent placements.",
        "image": "iim_kozhikode.jpg"
    },
    "iim indore": {
        "Full Name": "Indian Institute of Management Indore",
        "Short Name": "IIMI",
        "Location": "Indore, Madhya Pradesh",
        "Established": "1996",
        "Type": "Government",
        "Courses Offered": "MBA (PGP), IPM, Executive MBA, PhD",
        "Admission": "CAT, IPMAT",
        "Fees": "Approx. ₹21 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹30 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "BCG, Amazon, Deloitte, PwC, Infosys",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://www.iimidr.ac.in",
        "Review": "One of India's leading management institutes with excellent academics and placements.",
        "Why Choose": "Strong alumni network, excellent faculty and high placement records.",
        "image": "iim_indore.jpg"
    },
    "fms delhi": {
        "Full Name": "Faculty of Management Studies, University of Delhi",
        "Short Name": "FMS Delhi",
        "Location": "New Delhi",
        "Established": "1954",
        "Type": "Government",
        "Courses Offered": "MBA, Executive MBA, PhD",
        "Admission": "CAT",
        "Fees": "Approx. ₹2 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹34 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "McKinsey, BCG, Amazon, Microsoft, Aditya Birla Group",
        "Hostel": "Limited",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Library, Wi-Fi Campus, Computer Labs, Seminar Hall",
        "Official Website": "https://fms.edu",
        "Review": "One of India's best MBA colleges with excellent ROI and placements.",
        "Why Choose": "Low fees, outstanding placements and strong alumni network.",
        "image": "fms_delhi.jpg"
    },
    "xlri jamshedpur": {
        "Full Name": "XLRI - Xavier School of Management",
        "Short Name": "XLRI",
        "Location": "Jamshedpur, Jharkhand",
        "Established": "1949",
        "Type": "Private",
        "Courses Offered": "PGDM (BM), PGDM (HRM), Executive PGDM, FPM",
        "Admission": "XAT, GMAT",
        "Fees": "Approx. ₹30 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹29 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "BCG, Bain, Accenture, Deloitte, Amazon, Tata",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Gymnasium",
        "Official Website": "https://xlri.ac.in",
        "Review": "India's oldest and one of the best private business schools.",
        "Why Choose": "Excellent placements, top HR program, strong alumni network.",
        "image": "xlri.jpg"
    },
    "kj somaiya": {
        "Full Name": "K J Somaiya Institute of Management",
        "Short Name": "KJSIM",
        "Location": "Mumbai, Maharashtra",
        "Established": "1981",
        "Type": "Private",
        "Courses Offered": "MBA, MBA Executive, PhD",
        "Admission": "CAT, XAT, CMAT, NMAT",
        "Fees": "Approx. ₹22 Lakh (2 Years)",
        "Placement": "Very Good",
        "Average Package": "Approx. ₹13 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "Deloitte, KPMG, EY, Infosys, ICICI Bank",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Auditorium",
        "Official Website": "https://kjsim.somaiya.edu",
        "Review": "One of Mumbai's leading private management institutes.",
        "Why Choose": "Strong industry connections, modern campus and good placements.",
        "image": "kj_somaiya.jpg"
    },
    "spjimr": {
        "Full Name": "S. P. Jain Institute of Management and Research",
        "Short Name": "SPJIMR",
        "Location": "Mumbai, Maharashtra",
        "Established": "1981",
        "Type": "Private",
        "Courses Offered": "PGDM, PGPM, Executive MBA, FPM",
        "Admission": "CAT, GMAT",
        "Fees": "Approx. ₹24 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹33 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "BCG, Bain, Amazon, Deloitte, Accenture",
        "Hostel": "Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Hostel, Wi-Fi Campus, Computer Labs, Medical Centre, Auditorium",
        "Official Website": "https://www.spjimr.org",
        "Review": "One of India's top private management institutes with outstanding placements.",
        "Why Choose": "Industry-oriented curriculum, global exposure and excellent placements.",
        "image": "spjimr.jpg"
    },
    "jbims": {
        "Full Name": "Jamnalal Bajaj Institute of Management Studies",
        "Short Name": "JBIMS",
        "Location": "Mumbai, Maharashtra",
        "Established": "1965",
        "Type": "Government",
        "Courses Offered": "MBA, MMS, MSc Finance, PhD",
        "Admission": "MAH MBA CET, CAT, CMAT",
        "Fees": "Approx. ₹6 Lakh (2 Years)",
        "Placement": "Excellent",
        "Average Package": "Approx. ₹28 LPA",
        "Highest Package": "Varies Every Year",
        "Top Recruiters": "Goldman Sachs, JP Morgan, Deloitte, Accenture, HDFC Bank",
        "Hostel": "Limited",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Library, Wi-Fi Campus, Computer Labs, Seminar Hall",
        "Official Website": "https://jbims.edu",
        "Review": "One of India's premier management institutes with outstanding ROI and placements.",
        "Why Choose": "Low fees, excellent placements, strong alumni network and industry reputation.",
        "image": "jbims.jpg"
    },
    "bk birla college": {
        "Full Name": "B. K. Birla College of Arts, Science and Commerce",
        "Short Name": "BK Birla College",
        "Location": "Kalyan, Maharashtra",
        "Established": "1972",
        "Type": "Private",
        "Courses Offered": "BA, BCom, BSc, BMS, BAF, BBI, BMM, MSc, MCom, PhD",
        "Admission": "Merit Based",
        "Fees": "As per University Norms",
        "Placement": "Good",
        "Average Package": "Approx. ₹3 LPA",
        "Facilities": "Library, Computer Labs, Wi-Fi Campus, Auditorium, Sports Complex",
        "Official Website": "https://bkbirlacollegekalyan.com",
        "Review": "One of the leading colleges affiliated with the University of Mumbai.",
        "Why Choose": "Good academics, experienced faculty, affordable fees and placement support.",
        "image": "bk_birla.jpg"
    },
    "rj college": {
        "Full Name": "Hindi Vidya Prachar Samiti's Ramniranjan Jhunjhunwala College of Arts, Science & Commerce",
        "Short Name": "RJ College",
        "Location": "Ghatkopar, Mumbai, Maharashtra",
        "Established": "1963",
        "Type": "Private",
        "Courses Offered": "BA, BCom, BSc, BMS, BAF, BBI, BMM, BSc IT, BSc CS, MSc, MCom",
        "Admission": "Merit Based",
        "Fees": "As per University Norms",
        "Placement": "Good",
        "Average Package": "Approx. ₹4.5 LPA",
        "Highest Package": "Approx. ₹12 LPA",
        "Top Recruiters": "TCS, Infosys, Wipro, Capgemini, Accenture",
        "Hostel": "Not Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Library, Computer Labs, Wi-Fi Campus, Auditorium, Gymkhana",
        "Official Website": "https://www.rjcollege.edu.in",
        "Review": "A reputed autonomous college affiliated with the University of Mumbai.",
        "Why Choose": "Quality education, autonomous curriculum, experienced faculty and good placement support.",
        "image": "rj_college.jpg"
    },
    "achievers college": {
        "Full Name": "Achievers College of Commerce and Management",
        "Short Name": "Achievers College",
        "Location": "Kalyan, Maharashtra",
        "Established": "2015",
        "Type": "Private",
        "Courses Offered": "BCom, BMS, BAF, BBI, BSc IT, BSc CS",
        "Admission": "Merit Based",
        "Fees": "As per College Norms",
        "Placement": "Good",
        "Average Package": "Approx. ₹3.5 LPA",
        "Highest Package": "Approx. ₹8 LPA",
        "Top Recruiters": "TCS, Wipro, Infosys, Tech Mahindra",
        "Hostel": "Not Available",
        "Library": "Available",
        "Sports": "Indoor & Outdoor Sports",
        "Facilities": "Library, Computer Labs, Wi-Fi Campus, Seminar Hall",
        "Official Website": "https://achievers.edu.in",
        "Review": "A growing college offering commerce and management education.",
        "Why Choose": "Affordable fees, practical learning and student-friendly environment.",
        "image": "achievers.jpg"
    }
}
@app.route("/", methods=["GET", "POST"])
def home():
    result = None

    if request.method == "POST":
        college_name = request.form.get("college", "").strip().lower()

        if college_name in colleges:
            result = colleges[college_name]
        else:
            result = {"Error": "College not found in database."}

    return render_template("index.html", result=result)


@app.route("/top-colleges")
def top_colleges():
    return render_template("top_colleges.html")


@app.route("/compare", methods=["GET", "POST"])
def compare():
    college1 = None
    college2 = None

    if request.method == "POST":
        c1 = request.form.get("college1", "").strip().lower()
        c2 = request.form.get("college2", "").strip().lower()

        if c1 in colleges:
            college1 = colleges[c1]

        if c2 in colleges:
            college2 = colleges[c2]

    return render_template(
        "compare.html",
        colleges=colleges,
        college1=college1,
        college2=college2
    )


if __name__ == "__main__":
    app.run(debug=True)